#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3
clone:
  depth: 'full'

pipelines:
 branches:
  develop:
    #- parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
           name: Adobe Repo Update
           script: 
            - apt-get update && apt-get install -y unzip git
            - git remote add adobe https://git.cloudmanager.adobe.com/tfal/TFALProgram3-p51554-uk33827/
            - git config user.email "muhammad.hassan@tfal.com.au"
            - git config user.name "Muhammad Hassan"
            - git config credential.username $GIT_User            
            - git config credential.helper "!echo password=$GIT_Token; echo"                        
            - git checkout develop 
            - git pull
            - git push -f -u adobe develop
      - step:
           name: Build and deploy storybook
           image: node:16.14.2
           script:              
              - cd ui.frontend
              #- mv .npmrc_config .npmrc              
              - npm install --save --legacy-peer-deps                           
              - apt-get update && apt-get install -y unzip git
              - git config --global user.name "mhassan_TFA"
              - git config --global user.email "muhammad.hassan@tfal.com.au"                                        
              - git clone https://mhassan_TFA:$BITBUCKET_APP_PASSWORD@bitbucket.org/ToyotaFinanceAustralia/toyotafinanceaustralia.bitbucket.io.git
              - touch myfile.txt
              - cp myfile.txt toyotafinanceaustralia.bitbucket.io              
              - cd toyotafinanceaustralia.bitbucket.io 
              - git checkout master
              - git add -A
              - git commit -m "`date`"
              - git push -f
              - git rm -r *
              - git commit -m "clean repo"
              - git push
              - cd -
              - npm run build-storybook
              - cp -r storybook-static/. toyotafinanceaustralia.bitbucket.io                           
              - cd toyotafinanceaustralia.bitbucket.io               
              - git add -A
              - git commit -m "`date`"
              - git push -f
  stage:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
           name: Adobe Repo Update
           script: 
            - apt-get update && apt-get install -y unzip git
            - git remote add adobe https://git.cloudmanager.adobe.com/tfal/TFALProgram3-p51554-uk33827/
            - git config user.email "muhammad.hassan@tfal.com.au"
            - git config user.name "Muhammad Hassan"
            - git config credential.username $GIT_User            
            - git config credential.helper "!echo password=$GIT_Token; echo"                        
            - git checkout stage 
            - git pull
            - git push -f -u adobe stage
  sit:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
           name: Adobe Repo Update
           script: 
            - apt-get update && apt-get install -y unzip git
            - git remote add adobe https://git.cloudmanager.adobe.com/tfal/TFALProgram3-p51554-uk33827/
            - git config user.email "muhammad.hassan@tfal.com.au"
            - git config user.name "Muhammad Hassan"
            - git config credential.username $GIT_User            
            - git config credential.helper "!echo password=$GIT_Token; echo"                        
            - git checkout sit
            - git pull
            - git push -f -u adobe sit
  uat:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
           name: Adobe Repo Update
           script: 
            - apt-get update && apt-get install -y unzip git
            - git remote add adobe https://git.cloudmanager.adobe.com/tfal/TFALProgram3-p51554-uk33827/
            - git config user.email "muhammad.hassan@tfal.com.au"
            - git config user.name "Muhammad Hassan"
            - git config credential.username $GIT_User            
            - git config credential.helper "!echo password=$GIT_Token; echo"                        
            - git checkout uat
            - git pull
            - git push -f -u adobe uat
  master:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
           name: Adobe Repo Update
           script: 
            - apt-get update && apt-get install -y unzip git
            - git remote add adobe https://git.cloudmanager.adobe.com/tfal/TFALProgram3-p51554-uk33827/
            - git config user.email "muhammad.hassan@tfal.com.au"
            - git config user.name "Muhammad Hassan"
            - git config credential.username $GIT_User            
            - git config credential.helper "!echo password=$GIT_Token; echo"                        
            - git checkout master
            - git pull
            - git push -f -u adobe master